# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hannah_pb2 as hannah__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hannah_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HannahServiceStub(object):
    """============================================================
    Hannah gRPC Service

    Allows external services (Telegram bot, web UI, etc.) to:
    - query and manage the user registry
    - submit text commands and receive answers
    - trigger TTS announcements on satellites
    - inspect registered satellites
    - query live car state
    - subscribe to a stream of Hannah events (car parked, resident arrived, …)
    - register as a satellite audio proxy (Go gRPC proxy replaces UDP server)
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/hannah.HannahService/GetUsers',
                request_serializer=hannah__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=hannah__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/hannah.HannahService/GetUser',
                request_serializer=hannah__pb2.GetUserRequest.SerializeToString,
                response_deserializer=hannah__pb2.UserResponse.FromString,
                _registered_method=True)
        self.LinkAccount = channel.unary_unary(
                '/hannah.HannahService/LinkAccount',
                request_serializer=hannah__pb2.LinkAccountRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UnlinkAccount = channel.unary_unary(
                '/hannah.HannahService/UnlinkAccount',
                request_serializer=hannah__pb2.UnlinkAccountRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetTrustLevel = channel.unary_unary(
                '/hannah.HannahService/SetTrustLevel',
                request_serializer=hannah__pb2.SetTrustLevelRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SetSystemMessages = channel.unary_unary(
                '/hannah.HannahService/SetSystemMessages',
                request_serializer=hannah__pb2.SetSystemMessagesRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetDevices = channel.unary_unary(
                '/hannah.HannahService/GetDevices',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetDevicesResponse.FromString,
                _registered_method=True)
        self.ControlDevice = channel.unary_unary(
                '/hannah.HannahService/ControlDevice',
                request_serializer=hannah__pb2.ControlDeviceRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SubmitText = channel.unary_unary(
                '/hannah.HannahService/SubmitText',
                request_serializer=hannah__pb2.SubmitTextRequest.SerializeToString,
                response_deserializer=hannah__pb2.SubmitTextResponse.FromString,
                _registered_method=True)
        self.SubmitVoice = channel.unary_unary(
                '/hannah.HannahService/SubmitVoice',
                request_serializer=hannah__pb2.SubmitVoiceRequest.SerializeToString,
                response_deserializer=hannah__pb2.SubmitVoiceResponse.FromString,
                _registered_method=True)
        self.Announce = channel.unary_unary(
                '/hannah.HannahService/Announce',
                request_serializer=hannah__pb2.AnnounceRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetSatellites = channel.unary_unary(
                '/hannah.HannahService/GetSatellites',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetSatellitesResponse.FromString,
                _registered_method=True)
        self.GetCarState = channel.unary_unary(
                '/hannah.HannahService/GetCarState',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.CarStateResponse.FromString,
                _registered_method=True)
        self.GetAllCarStates = channel.unary_unary(
                '/hannah.HannahService/GetAllCarStates',
                request_serializer=hannah__pb2.Empty.SerializeToString,
                response_deserializer=hannah__pb2.GetAllCarStatesResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/hannah.HannahService/SubscribeEvents',
                request_serializer=hannah__pb2.EventFilter.SerializeToString,
                response_deserializer=hannah__pb2.HannahEvent.FromString,
                _registered_method=True)
        self.RegisterProxy = channel.stream_stream(
                '/hannah.HannahService/RegisterProxy',
                request_serializer=hannah__pb2.ProxyHeartbeat.SerializeToString,
                response_deserializer=hannah__pb2.ProxyCommand.FromString,
                _registered_method=True)
        self.SubmitSatelliteAudio = channel.unary_unary(
                '/hannah.HannahService/SubmitSatelliteAudio',
                request_serializer=hannah__pb2.SubmitSatelliteAudioRequest.SerializeToString,
                response_deserializer=hannah__pb2.SubmitSatelliteAudioResponse.FromString,
                _registered_method=True)
        self.NotifySatelliteRegistered = channel.unary_unary(
                '/hannah.HannahService/NotifySatelliteRegistered',
                request_serializer=hannah__pb2.SatelliteRegistration.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.NotifySatelliteGone = channel.unary_unary(
                '/hannah.HannahService/NotifySatelliteGone',
                request_serializer=hannah__pb2.SatelliteRegistration.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.EnrollVoiceprint = channel.unary_unary(
                '/hannah.HannahService/EnrollVoiceprint',
                request_serializer=hannah__pb2.EnrollVoiceprintRequest.SerializeToString,
                response_deserializer=hannah__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AgentConnect = channel.stream_stream(
                '/hannah.HannahService/AgentConnect',
                request_serializer=hannah__pb2.AgentMessage.SerializeToString,
                response_deserializer=hannah__pb2.AgentCommand.FromString,
                _registered_method=True)


class HannahServiceServicer(object):
    """============================================================
    Hannah gRPC Service

    Allows external services (Telegram bot, web UI, etc.) to:
    - query and manage the user registry
    - submit text commands and receive answers
    - trigger TTS announcements on satellites
    - inspect registered satellites
    - query live car state
    - subscribe to a stream of Hannah events (car parked, resident arrived, …)
    - register as a satellite audio proxy (Go gRPC proxy replaces UDP server)
    ============================================================

    """

    def GetUsers(self, request, context):
        """--- User Registry ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrustLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSystemMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevices(self, request, context):
        """--- Device Control Menu ---
        Returns all rooms and devices with current state — for building control menus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlDevice(self, request, context):
        """Directly set a device state (bypasses NLU). Trust level check is done by the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitText(self, request, context):
        """--- Control ---
        Submit a plain-text command; Hannah processes it through NLU and returns the answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitVoice(self, request, context):
        """Submit a voice message (OGG/Opus bytes); Hannah does STT → NLU → TTS and returns the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Announce(self, request, context):
        """Send a TTS announcement to one satellite or all ("all").
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSatellites(self, request, context):
        """List all currently registered UDP satellites.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarState(self, request, context):
        """--- Car ---
        Returns the current cached car state (available=false if no data received yet).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCarStates(self, request, context):
        """Returns all tracked car states (one per configured car).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """--- Event stream ---
        Opens a server-side stream; Hannah pushes events as they occur.
        Pass event_types to filter (empty = all events).
        Known event types: "car.parked", "resident.arrived", "resident.departed"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterProxy(self, request_iterator, context):
        """--- Satellite Proxy (Go gRPC proxy) ---
        Bidirectional keepalive stream. Proxy sends heartbeats; Hannah sends TTS
        audio commands back (for announcements). While this stream is open, Hannah
        disables its own UDP server. If the stream drops, Hannah re-enables UDP.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSatelliteAudio(self, request, context):
        """Submit a complete satellite audio session for processing.
        Hannah runs the full pipeline (STT → NLU → TTS → MQTT status) and returns
        the result so the proxy can play TTS audio back to the satellite.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifySatelliteRegistered(self, request, context):
        """Notify Hannah that a satellite registered or disconnected via the proxy.
        Hannah updates its room registry (hannah/rooms MQTT) immediately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifySatelliteGone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollVoiceprint(self, request, context):
        """--- Speaker Enrollment ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentConnect(self, request_iterator, context):
        """--- ioBroker Agent ---
        Single bidirectional stream between the HannahAgent ioBroker adapter and Hannah Core.
        The adapter pushes state updates (device states, presence, text commands);
        Hannah pushes device-control commands and on-demand state-subscription requests back.
        The adapter initiates the connection; if Hannah restarts, the adapter reconnects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HannahServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=hannah__pb2.GetUsersRequest.FromString,
                    response_serializer=hannah__pb2.GetUsersResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=hannah__pb2.GetUserRequest.FromString,
                    response_serializer=hannah__pb2.UserResponse.SerializeToString,
            ),
            'LinkAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkAccount,
                    request_deserializer=hannah__pb2.LinkAccountRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'UnlinkAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkAccount,
                    request_deserializer=hannah__pb2.UnlinkAccountRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SetTrustLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrustLevel,
                    request_deserializer=hannah__pb2.SetTrustLevelRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SetSystemMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSystemMessages,
                    request_deserializer=hannah__pb2.SetSystemMessagesRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevices,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetDevicesResponse.SerializeToString,
            ),
            'ControlDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlDevice,
                    request_deserializer=hannah__pb2.ControlDeviceRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'SubmitText': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitText,
                    request_deserializer=hannah__pb2.SubmitTextRequest.FromString,
                    response_serializer=hannah__pb2.SubmitTextResponse.SerializeToString,
            ),
            'SubmitVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitVoice,
                    request_deserializer=hannah__pb2.SubmitVoiceRequest.FromString,
                    response_serializer=hannah__pb2.SubmitVoiceResponse.SerializeToString,
            ),
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=hannah__pb2.AnnounceRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'GetSatellites': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSatellites,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetSatellitesResponse.SerializeToString,
            ),
            'GetCarState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarState,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.CarStateResponse.SerializeToString,
            ),
            'GetAllCarStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCarStates,
                    request_deserializer=hannah__pb2.Empty.FromString,
                    response_serializer=hannah__pb2.GetAllCarStatesResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=hannah__pb2.EventFilter.FromString,
                    response_serializer=hannah__pb2.HannahEvent.SerializeToString,
            ),
            'RegisterProxy': grpc.stream_stream_rpc_method_handler(
                    servicer.RegisterProxy,
                    request_deserializer=hannah__pb2.ProxyHeartbeat.FromString,
                    response_serializer=hannah__pb2.ProxyCommand.SerializeToString,
            ),
            'SubmitSatelliteAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSatelliteAudio,
                    request_deserializer=hannah__pb2.SubmitSatelliteAudioRequest.FromString,
                    response_serializer=hannah__pb2.SubmitSatelliteAudioResponse.SerializeToString,
            ),
            'NotifySatelliteRegistered': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifySatelliteRegistered,
                    request_deserializer=hannah__pb2.SatelliteRegistration.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'NotifySatelliteGone': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifySatelliteGone,
                    request_deserializer=hannah__pb2.SatelliteRegistration.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'EnrollVoiceprint': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollVoiceprint,
                    request_deserializer=hannah__pb2.EnrollVoiceprintRequest.FromString,
                    response_serializer=hannah__pb2.StatusResponse.SerializeToString,
            ),
            'AgentConnect': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentConnect,
                    request_deserializer=hannah__pb2.AgentMessage.FromString,
                    response_serializer=hannah__pb2.AgentCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hannah.HannahService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hannah.HannahService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HannahService(object):
    """============================================================
    Hannah gRPC Service

    Allows external services (Telegram bot, web UI, etc.) to:
    - query and manage the user registry
    - submit text commands and receive answers
    - trigger TTS announcements on satellites
    - inspect registered satellites
    - query live car state
    - subscribe to a stream of Hannah events (car parked, resident arrived, …)
    - register as a satellite audio proxy (Go gRPC proxy replaces UDP server)
    ============================================================

    """

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetUsers',
            hannah__pb2.GetUsersRequest.SerializeToString,
            hannah__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetUser',
            hannah__pb2.GetUserRequest.SerializeToString,
            hannah__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/LinkAccount',
            hannah__pb2.LinkAccountRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/UnlinkAccount',
            hannah__pb2.UnlinkAccountRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTrustLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetTrustLevel',
            hannah__pb2.SetTrustLevelRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSystemMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SetSystemMessages',
            hannah__pb2.SetSystemMessagesRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetDevices',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/ControlDevice',
            hannah__pb2.ControlDeviceRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SubmitText',
            hannah__pb2.SubmitTextRequest.SerializeToString,
            hannah__pb2.SubmitTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SubmitVoice',
            hannah__pb2.SubmitVoiceRequest.SerializeToString,
            hannah__pb2.SubmitVoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/Announce',
            hannah__pb2.AnnounceRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSatellites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetSatellites',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetSatellitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCarState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetCarState',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.CarStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCarStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/GetAllCarStates',
            hannah__pb2.Empty.SerializeToString,
            hannah__pb2.GetAllCarStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hannah.HannahService/SubscribeEvents',
            hannah__pb2.EventFilter.SerializeToString,
            hannah__pb2.HannahEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterProxy(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hannah.HannahService/RegisterProxy',
            hannah__pb2.ProxyHeartbeat.SerializeToString,
            hannah__pb2.ProxyCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSatelliteAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/SubmitSatelliteAudio',
            hannah__pb2.SubmitSatelliteAudioRequest.SerializeToString,
            hannah__pb2.SubmitSatelliteAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifySatelliteRegistered(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/NotifySatelliteRegistered',
            hannah__pb2.SatelliteRegistration.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifySatelliteGone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/NotifySatelliteGone',
            hannah__pb2.SatelliteRegistration.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrollVoiceprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hannah.HannahService/EnrollVoiceprint',
            hannah__pb2.EnrollVoiceprintRequest.SerializeToString,
            hannah__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentConnect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hannah.HannahService/AgentConnect',
            hannah__pb2.AgentMessage.SerializeToString,
            hannah__pb2.AgentCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
