// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hannah.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_hannah_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_hannah_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Uuid        string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RoomieId    string                 `protobuf:"bytes,2,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	TrustLevel  int32                  `protobuf:"varint,4,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	Active      bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	// linked_accounts: service → account_id  (e.g. "telegram" → "123456789")
	LinkedAccounts map[string]string `protobuf:"bytes,6,rep,name=linked_accounts,json=linkedAccounts,proto3" json:"linked_accounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_hannah_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetTrustLevel() int32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetLinkedAccounts() map[string]string {
	if x != nil {
		return x.LinkedAccounts
	}
	return nil
}

type GetUsersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeInactive bool                   `protobuf:"varint,1,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_hannah_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_hannah_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Exactly one of the lookup fields should be set.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*GetUserRequest_RoomieId
	//	*GetUserRequest_Uuid
	//	*GetUserRequest_LinkedAccount
	Lookup        isGetUserRequest_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_hannah_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetLookup() isGetUserRequest_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *GetUserRequest) GetRoomieId() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_RoomieId); ok {
			return x.RoomieId
		}
	}
	return ""
}

func (x *GetUserRequest) GetUuid() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Uuid); ok {
			return x.Uuid
		}
	}
	return ""
}

func (x *GetUserRequest) GetLinkedAccount() *LinkedAccountLookup {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_LinkedAccount); ok {
			return x.LinkedAccount
		}
	}
	return nil
}

type isGetUserRequest_Lookup interface {
	isGetUserRequest_Lookup()
}

type GetUserRequest_RoomieId struct {
	RoomieId string `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3,oneof"`
}

type GetUserRequest_Uuid struct {
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"`
}

type GetUserRequest_LinkedAccount struct {
	LinkedAccount *LinkedAccountLookup `protobuf:"bytes,3,opt,name=linked_account,json=linkedAccount,proto3,oneof"`
}

func (*GetUserRequest_RoomieId) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Uuid) isGetUserRequest_Lookup() {}

func (*GetUserRequest_LinkedAccount) isGetUserRequest_Lookup() {}

type LinkedAccountLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedAccountLookup) Reset() {
	*x = LinkedAccountLookup{}
	mi := &file_hannah_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedAccountLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccountLookup) ProtoMessage() {}

func (x *LinkedAccountLookup) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccountLookup.ProtoReflect.Descriptor instead.
func (*LinkedAccountLookup) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{6}
}

func (x *LinkedAccountLookup) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LinkedAccountLookup) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // only valid when found == true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_hannah_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{7}
}

func (x *UserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LinkAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomieId      string                 `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkAccountRequest) Reset() {
	*x = LinkAccountRequest{}
	mi := &file_hannah_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkAccountRequest) ProtoMessage() {}

func (x *LinkAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkAccountRequest.ProtoReflect.Descriptor instead.
func (*LinkAccountRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{8}
}

func (x *LinkAccountRequest) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *LinkAccountRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LinkAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UnlinkAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkAccountRequest) Reset() {
	*x = UnlinkAccountRequest{}
	mi := &file_hannah_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkAccountRequest) ProtoMessage() {}

func (x *UnlinkAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkAccountRequest.ProtoReflect.Descriptor instead.
func (*UnlinkAccountRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{9}
}

func (x *UnlinkAccountRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *UnlinkAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type SetTrustLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomieId      string                 `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // clamped to [0, 10]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTrustLevelRequest) Reset() {
	*x = SetTrustLevelRequest{}
	mi := &file_hannah_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTrustLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrustLevelRequest) ProtoMessage() {}

func (x *SetTrustLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrustLevelRequest.ProtoReflect.Descriptor instead.
func (*SetTrustLevelRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{10}
}

func (x *SetTrustLevelRequest) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *SetTrustLevelRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SubmitTextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Identifies the calling service and its user, so Hannah can look up
	// the corresponding roomie via linked_accounts.
	SourceService string `protobuf:"bytes,2,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // e.g. "telegram"
	SourceUserId  string `protobuf:"bytes,3,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`  // e.g. Telegram chat_id as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTextRequest) Reset() {
	*x = SubmitTextRequest{}
	mi := &file_hannah_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTextRequest) ProtoMessage() {}

func (x *SubmitTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTextRequest.ProtoReflect.Descriptor instead.
func (*SubmitTextRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SubmitTextRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *SubmitTextRequest) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

type SubmitTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`                           // text to send back to the user
	IntentName    string                 `protobuf:"bytes,2,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"` // e.g. "WeatherQuery", "TurnOn", "Unknown"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTextResponse) Reset() {
	*x = SubmitTextResponse{}
	mi := &file_hannah_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTextResponse) ProtoMessage() {}

func (x *SubmitTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTextResponse.ProtoReflect.Descriptor instead.
func (*SubmitTextResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitTextResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitTextResponse) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

type SubmitVoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         []byte                 `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`                                      // OGG/Opus audio bytes (from Telegram voice message)
	SourceService string                 `protobuf:"bytes,2,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // e.g. "telegram"
	SourceUserId  string                 `protobuf:"bytes,3,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`  // e.g. Telegram chat_id as string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVoiceRequest) Reset() {
	*x = SubmitVoiceRequest{}
	mi := &file_hannah_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoiceRequest) ProtoMessage() {}

func (x *SubmitVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoiceRequest.ProtoReflect.Descriptor instead.
func (*SubmitVoiceRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitVoiceRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *SubmitVoiceRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *SubmitVoiceRequest) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

type SubmitVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`                   // STT result (for display / caption)
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`                           // text answer from Hannah
	IntentName    string                 `protobuf:"bytes,3,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"` // e.g. "CarQuery" — caller may enrich the text reply
	AudioOgg      []byte                 `protobuf:"bytes,4,opt,name=audio_ogg,json=audioOgg,proto3" json:"audio_ogg,omitempty"`       // OGG/Opus TTS response (empty if TTS disabled or failed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVoiceResponse) Reset() {
	*x = SubmitVoiceResponse{}
	mi := &file_hannah_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVoiceResponse) ProtoMessage() {}

func (x *SubmitVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVoiceResponse.ProtoReflect.Descriptor instead.
func (*SubmitVoiceResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitVoiceResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *SubmitVoiceResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitVoiceResponse) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *SubmitVoiceResponse) GetAudioOgg() []byte {
	if x != nil {
		return x.AudioOgg
	}
	return nil
}

type AnnounceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"` // satellite device name, or "all" for broadcast
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	mi := &file_hannah_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{15}
}

func (x *AnnounceRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnnounceRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type Satellite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`       // room name as registered
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // IP:port of the UDP satellite
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Satellite) Reset() {
	*x = Satellite{}
	mi := &file_hannah_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Satellite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Satellite) ProtoMessage() {}

func (x *Satellite) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Satellite.ProtoReflect.Descriptor instead.
func (*Satellite) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{16}
}

func (x *Satellite) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Satellite) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Satellite) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetSatellitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Satellites    []*Satellite           `protobuf:"bytes,1,rep,name=satellites,proto3" json:"satellites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSatellitesResponse) Reset() {
	*x = GetSatellitesResponse{}
	mi := &file_hannah_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSatellitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSatellitesResponse) ProtoMessage() {}

func (x *GetSatellitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSatellitesResponse.ProtoReflect.Descriptor instead.
func (*GetSatellitesResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{17}
}

func (x *GetSatellitesResponse) GetSatellites() []*Satellite {
	if x != nil {
		return x.Satellites
	}
	return nil
}

type CarStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"` // false if no MQTT data received yet
	State         *CarStateProto         `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarStateResponse) Reset() {
	*x = CarStateResponse{}
	mi := &file_hannah_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStateResponse) ProtoMessage() {}

func (x *CarStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStateResponse.ProtoReflect.Descriptor instead.
func (*CarStateResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{18}
}

func (x *CarStateResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CarStateResponse) GetState() *CarStateProto {
	if x != nil {
		return x.State
	}
	return nil
}

type CarStateProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// position
	Latitude     float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude    float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address      string  `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	IsMoving     bool    `protobuf:"varint,4,opt,name=is_moving,json=isMoving,proto3" json:"is_moving,omitempty"`
	PositionDate int64   `protobuf:"varint,5,opt,name=position_date,json=positionDate,proto3" json:"position_date,omitempty"` // Unix timestamp (seconds)
	// status
	Odometer       int32  `protobuf:"varint,6,opt,name=odometer,proto3" json:"odometer,omitempty"`
	TotalRange     int32  `protobuf:"varint,7,opt,name=total_range,json=totalRange,proto3" json:"total_range,omitempty"`
	IsCarLocked    bool   `protobuf:"varint,8,opt,name=is_car_locked,json=isCarLocked,proto3" json:"is_car_locked,omitempty"`
	DoorLockStatus string `protobuf:"bytes,9,opt,name=door_lock_status,json=doorLockStatus,proto3" json:"door_lock_status,omitempty"`
	OverallStatus  string `protobuf:"bytes,10,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	// doors/windows: name → true (closed) / false (open)
	Doors   map[string]bool `protobuf:"bytes,11,rep,name=doors,proto3" json:"doors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Windows map[string]bool `protobuf:"bytes,12,rep,name=windows,proto3" json:"windows,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Roomie-ID des Fahrzeughalters (leer = kein Owner-Filter)
	OwnerRoomie   string `protobuf:"bytes,13,opt,name=owner_roomie,json=ownerRoomie,proto3" json:"owner_roomie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarStateProto) Reset() {
	*x = CarStateProto{}
	mi := &file_hannah_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStateProto) ProtoMessage() {}

func (x *CarStateProto) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStateProto.ProtoReflect.Descriptor instead.
func (*CarStateProto) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{19}
}

func (x *CarStateProto) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CarStateProto) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CarStateProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CarStateProto) GetIsMoving() bool {
	if x != nil {
		return x.IsMoving
	}
	return false
}

func (x *CarStateProto) GetPositionDate() int64 {
	if x != nil {
		return x.PositionDate
	}
	return 0
}

func (x *CarStateProto) GetOdometer() int32 {
	if x != nil {
		return x.Odometer
	}
	return 0
}

func (x *CarStateProto) GetTotalRange() int32 {
	if x != nil {
		return x.TotalRange
	}
	return 0
}

func (x *CarStateProto) GetIsCarLocked() bool {
	if x != nil {
		return x.IsCarLocked
	}
	return false
}

func (x *CarStateProto) GetDoorLockStatus() string {
	if x != nil {
		return x.DoorLockStatus
	}
	return ""
}

func (x *CarStateProto) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

func (x *CarStateProto) GetDoors() map[string]bool {
	if x != nil {
		return x.Doors
	}
	return nil
}

func (x *CarStateProto) GetWindows() map[string]bool {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *CarStateProto) GetOwnerRoomie() string {
	if x != nil {
		return x.OwnerRoomie
	}
	return ""
}

type EventFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If empty, subscribe to all event types.
	EventTypes    []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_hannah_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{20}
}

func (x *EventFilter) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type HannahEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "car.parked" | "resident.arrived" | "resident.departed"
	Timestamp string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // ISO 8601 UTC
	// Types that are valid to be assigned to Payload:
	//
	//	*HannahEvent_CarState
	//	*HannahEvent_ResidentEvent
	Payload       isHannahEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HannahEvent) Reset() {
	*x = HannahEvent{}
	mi := &file_hannah_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HannahEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HannahEvent) ProtoMessage() {}

func (x *HannahEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HannahEvent.ProtoReflect.Descriptor instead.
func (*HannahEvent) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{21}
}

func (x *HannahEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HannahEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HannahEvent) GetPayload() isHannahEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HannahEvent) GetCarState() *CarStateProto {
	if x != nil {
		if x, ok := x.Payload.(*HannahEvent_CarState); ok {
			return x.CarState
		}
	}
	return nil
}

func (x *HannahEvent) GetResidentEvent() *ResidentEventProto {
	if x != nil {
		if x, ok := x.Payload.(*HannahEvent_ResidentEvent); ok {
			return x.ResidentEvent
		}
	}
	return nil
}

type isHannahEvent_Payload interface {
	isHannahEvent_Payload()
}

type HannahEvent_CarState struct {
	CarState *CarStateProto `protobuf:"bytes,10,opt,name=car_state,json=carState,proto3,oneof"`
}

type HannahEvent_ResidentEvent struct {
	ResidentEvent *ResidentEventProto `protobuf:"bytes,11,opt,name=resident_event,json=residentEvent,proto3,oneof"`
}

func (*HannahEvent_CarState) isHannahEvent_Payload() {}

func (*HannahEvent_ResidentEvent) isHannahEvent_Payload() {}

type ResidentEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomieId      string                 `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"` // "arrived" | "departed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResidentEventProto) Reset() {
	*x = ResidentEventProto{}
	mi := &file_hannah_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResidentEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResidentEventProto) ProtoMessage() {}

func (x *ResidentEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResidentEventProto.ProtoReflect.Descriptor instead.
func (*ResidentEventProto) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{22}
}

func (x *ResidentEventProto) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *ResidentEventProto) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResidentEventProto) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

// Sent by the proxy periodically to keep the RegisterProxy stream alive.
type ProxyHeartbeat struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ProxyId string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"` // human-readable identifier, e.g. "hannah-proxy-living-room"
	// UDP address the proxy is listening on for satellite connections.
	// When set, Hannah publishes this address to the discovery topic so
	// satellites connect to the proxy instead of Hannah's own UDP server.
	UdpHost       string `protobuf:"bytes,2,opt,name=udp_host,json=udpHost,proto3" json:"udp_host,omitempty"`  // advertise host, e.g. "192.168.8.5"
	UdpPort       int32  `protobuf:"varint,3,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"` // UDP port, e.g. 7775
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyHeartbeat) Reset() {
	*x = ProxyHeartbeat{}
	mi := &file_hannah_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHeartbeat) ProtoMessage() {}

func (x *ProxyHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHeartbeat.ProtoReflect.Descriptor instead.
func (*ProxyHeartbeat) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{23}
}

func (x *ProxyHeartbeat) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyHeartbeat) GetUdpHost() string {
	if x != nil {
		return x.UdpHost
	}
	return ""
}

func (x *ProxyHeartbeat) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

// Sent by Hannah to the proxy over the RegisterProxy stream.
type ProxyCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ProxyCommand_Ack
	//	*ProxyCommand_PlayAudio
	Command       isProxyCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyCommand) Reset() {
	*x = ProxyCommand{}
	mi := &file_hannah_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyCommand) ProtoMessage() {}

func (x *ProxyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyCommand.ProtoReflect.Descriptor instead.
func (*ProxyCommand) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{24}
}

func (x *ProxyCommand) GetCommand() isProxyCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProxyCommand) GetAck() *ProxyAck {
	if x != nil {
		if x, ok := x.Command.(*ProxyCommand_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ProxyCommand) GetPlayAudio() *PlayAudioCommand {
	if x != nil {
		if x, ok := x.Command.(*ProxyCommand_PlayAudio); ok {
			return x.PlayAudio
		}
	}
	return nil
}

type isProxyCommand_Command interface {
	isProxyCommand_Command()
}

type ProxyCommand_Ack struct {
	Ack *ProxyAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // initial confirmation when stream is established
}

type ProxyCommand_PlayAudio struct {
	PlayAudio *PlayAudioCommand `protobuf:"bytes,2,opt,name=play_audio,json=playAudio,proto3,oneof"` // Hannah wants the proxy to play TTS on a satellite
}

func (*ProxyCommand_Ack) isProxyCommand_Command() {}

func (*ProxyCommand_PlayAudio) isProxyCommand_Command() {}

// Sent once by Hannah after RegisterProxy stream is established.
type ProxyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UdpDisabled   bool                   `protobuf:"varint,1,opt,name=udp_disabled,json=udpDisabled,proto3" json:"udp_disabled,omitempty"` // true = Hannah has disabled its own UDP server
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                             // human-readable status, e.g. "UDP server stopped"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyAck) Reset() {
	*x = ProxyAck{}
	mi := &file_hannah_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyAck) ProtoMessage() {}

func (x *ProxyAck) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyAck.ProtoReflect.Descriptor instead.
func (*ProxyAck) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{25}
}

func (x *ProxyAck) GetUdpDisabled() bool {
	if x != nil {
		return x.UdpDisabled
	}
	return false
}

func (x *ProxyAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Hannah instructs the proxy to play TTS audio on a specific satellite.
// Used for announcements and other server-initiated audio.
type PlayAudioCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // satellite device name (as registered via UDP or proxy)
	AudioPcm      []byte                 `protobuf:"bytes,2,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g. 24000 (Azure) or 16000 (Piper)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayAudioCommand) Reset() {
	*x = PlayAudioCommand{}
	mi := &file_hannah_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayAudioCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayAudioCommand) ProtoMessage() {}

func (x *PlayAudioCommand) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayAudioCommand.ProtoReflect.Descriptor instead.
func (*PlayAudioCommand) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{26}
}

func (x *PlayAudioCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PlayAudioCommand) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *PlayAudioCommand) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// Sent by the proxy when a satellite has finished recording an utterance.
type SubmitSatelliteAudioRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceId   string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // satellite device name
	Room       string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                                // room name (from proxy registration / config)
	AudioPcm   []byte                 `protobuf:"bytes,3,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono, 16000 Hz
	SampleRate int32                  `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // sample rate of the audio (typically 16000)
	// Optional: speaker identity provided by an upstream speaker-ID service.
	// Empty = anonymous (Hannah treats as unknown user).
	SpeakerRoomieId string `protobuf:"bytes,5,opt,name=speaker_roomie_id,json=speakerRoomieId,proto3" json:"speaker_roomie_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitSatelliteAudioRequest) Reset() {
	*x = SubmitSatelliteAudioRequest{}
	mi := &file_hannah_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSatelliteAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSatelliteAudioRequest) ProtoMessage() {}

func (x *SubmitSatelliteAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSatelliteAudioRequest.ProtoReflect.Descriptor instead.
func (*SubmitSatelliteAudioRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{27}
}

func (x *SubmitSatelliteAudioRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SubmitSatelliteAudioRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *SubmitSatelliteAudioRequest) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *SubmitSatelliteAudioRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SubmitSatelliteAudioRequest) GetSpeakerRoomieId() string {
	if x != nil {
		return x.SpeakerRoomieId
	}
	return ""
}

type SubmitSatelliteAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`                    // STT result
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`                            // text answer from Hannah
	IntentName    string                 `protobuf:"bytes,3,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"`  // e.g. "TurnOn", "CarQuery", "Unknown"
	AudioPcm      []byte                 `protobuf:"bytes,4,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // TTS response as raw PCM, 16-bit signed mono
	SampleRate    int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // sample rate of audio_pcm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSatelliteAudioResponse) Reset() {
	*x = SubmitSatelliteAudioResponse{}
	mi := &file_hannah_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSatelliteAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSatelliteAudioResponse) ProtoMessage() {}

func (x *SubmitSatelliteAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSatelliteAudioResponse.ProtoReflect.Descriptor instead.
func (*SubmitSatelliteAudioResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{28}
}

func (x *SubmitSatelliteAudioResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *SubmitSatelliteAudioResponse) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                     // full device prefix, e.g. "javascript.0.virtualDevice.Licht.EG.Wohnzimmer.DeckeSeite"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                 // display name, e.g. "DeckeSeite"
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                                                                         // e.g. "Licht", "Stecker", "Temperaturen"
	States        []string               `protobuf:"bytes,4,rep,name=states,proto3" json:"states,omitempty"`                                                                             // available state keys: "on", "level", "color", …
	Current       map[string]string      `protobuf:"bytes,5,rep,name=current,proto3" json:"current,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // current values as strings, e.g. {"on": "true", "level": "75"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_hannah_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{29}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DeviceInfo) GetStates() []string {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *DeviceInfo) GetCurrent() map[string]string {
	if x != nil {
		return x.Current
	}
	return nil
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`   // room_id (lowercase), e.g. "wohnzimmer"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // display name, e.g. "Wohnzimmer"
	Devices       []*DeviceInfo          `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_hannah_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{30}
}

func (x *RoomInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	mi := &file_hannah_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{31}
}

func (x *GetDevicesResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type ControlDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // DeviceInfo.id
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                       // state key: "on", "level", "color"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                       // string-serialised value: "true", "false", "50", "#FF0000"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlDeviceRequest) Reset() {
	*x = ControlDeviceRequest{}
	mi := &file_hannah_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDeviceRequest) ProtoMessage() {}

func (x *ControlDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDeviceRequest.ProtoReflect.Descriptor instead.
func (*ControlDeviceRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{32}
}

func (x *ControlDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ControlDeviceRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ControlDeviceRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EnrollVoiceprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomieId      string                 `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`        // whose voice this sample belongs to
	AudioPcm      []byte                 `protobuf:"bytes,2,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g. 16000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollVoiceprintRequest) Reset() {
	*x = EnrollVoiceprintRequest{}
	mi := &file_hannah_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollVoiceprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollVoiceprintRequest) ProtoMessage() {}

func (x *EnrollVoiceprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollVoiceprintRequest.ProtoReflect.Descriptor instead.
func (*EnrollVoiceprintRequest) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{33}
}

func (x *EnrollVoiceprintRequest) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *EnrollVoiceprintRequest) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *EnrollVoiceprintRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type SatelliteRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // satellite device name, e.g. "sat-wohnzimmer"
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                         // room name as reported by satellite, e.g. "Wohnzimmer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteRegistration) Reset() {
	*x = SatelliteRegistration{}
	mi := &file_hannah_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteRegistration) ProtoMessage() {}

func (x *SatelliteRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteRegistration.ProtoReflect.Descriptor instead.
func (*SatelliteRegistration) Descriptor() ([]byte, []int) {
	return file_hannah_proto_rawDescGZIP(), []int{34}
}

func (x *SatelliteRegistration) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SatelliteRegistration) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

var File_hannah_proto protoreflect.FileDescriptor

const file_hannah_proto_rawDesc = "" +
	"\n" +
	"\fhannah.proto\x12\x06hannah\"\a\n" +
	"\x05Empty\":\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa1\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1b\n" +
	"\troomie_id\x18\x02 \x01(\tR\broomieId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vtrust_level\x18\x04 \x01(\x05R\n" +
	"trustLevel\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12I\n" +
	"\x0flinked_accounts\x18\x06 \x03(\v2 .hannah.User.LinkedAccountsEntryR\x0elinkedAccounts\x1aA\n" +
	"\x13LinkedAccountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x0fGetUsersRequest\x12)\n" +
	"\x10include_inactive\x18\x01 \x01(\bR\x0fincludeInactive\"6\n" +
	"\x10GetUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.hannah.UserR\x05users\"\x95\x01\n" +
	"\x0eGetUserRequest\x12\x1d\n" +
	"\troomie_id\x18\x01 \x01(\tH\x00R\broomieId\x12\x14\n" +
	"\x04uuid\x18\x02 \x01(\tH\x00R\x04uuid\x12D\n" +
	"\x0elinked_account\x18\x03 \x01(\v2\x1b.hannah.LinkedAccountLookupH\x00R\rlinkedAccountB\b\n" +
	"\x06lookup\"N\n" +
	"\x13LinkedAccountLookup\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"F\n" +
	"\fUserResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12 \n" +
	"\x04user\x18\x02 \x01(\v2\f.hannah.UserR\x04user\"j\n" +
	"\x12LinkAccountRequest\x12\x1b\n" +
	"\troomie_id\x18\x01 \x01(\tR\broomieId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"O\n" +
	"\x14UnlinkAccountRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"I\n" +
	"\x14SetTrustLevelRequest\x12\x1b\n" +
	"\troomie_id\x18\x01 \x01(\tR\broomieId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"t\n" +
	"\x11SubmitTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12%\n" +
	"\x0esource_service\x18\x02 \x01(\tR\rsourceService\x12$\n" +
	"\x0esource_user_id\x18\x03 \x01(\tR\fsourceUserId\"M\n" +
	"\x12SubmitTextResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1f\n" +
	"\vintent_name\x18\x02 \x01(\tR\n" +
	"intentName\"w\n" +
	"\x12SubmitVoiceRequest\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\fR\x05audio\x12%\n" +
	"\x0esource_service\x18\x02 \x01(\tR\rsourceService\x12$\n" +
	"\x0esource_user_id\x18\x03 \x01(\tR\fsourceUserId\"\x8b\x01\n" +
	"\x13SubmitVoiceResponse\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1f\n" +
	"\vintent_name\x18\x03 \x01(\tR\n" +
	"intentName\x12\x1b\n" +
	"\taudio_ogg\x18\x04 \x01(\fR\baudioOgg\"=\n" +
	"\x0fAnnounceRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\"V\n" +
	"\tSatellite\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"J\n" +
	"\x15GetSatellitesResponse\x121\n" +
	"\n" +
	"satellites\x18\x01 \x03(\v2\x11.hannah.SatelliteR\n" +
	"satellites\"]\n" +
	"\x10CarStateResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12+\n" +
	"\x05state\x18\x02 \x01(\v2\x15.hannah.CarStateProtoR\x05state\"\xe6\x04\n" +
	"\rCarStateProto\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1b\n" +
	"\tis_moving\x18\x04 \x01(\bR\bisMoving\x12#\n" +
	"\rposition_date\x18\x05 \x01(\x03R\fpositionDate\x12\x1a\n" +
	"\bodometer\x18\x06 \x01(\x05R\bodometer\x12\x1f\n" +
	"\vtotal_range\x18\a \x01(\x05R\n" +
	"totalRange\x12\"\n" +
	"\ris_car_locked\x18\b \x01(\bR\visCarLocked\x12(\n" +
	"\x10door_lock_status\x18\t \x01(\tR\x0edoorLockStatus\x12%\n" +
	"\x0eoverall_status\x18\n" +
	" \x01(\tR\roverallStatus\x126\n" +
	"\x05doors\x18\v \x03(\v2 .hannah.CarStateProto.DoorsEntryR\x05doors\x12<\n" +
	"\awindows\x18\f \x03(\v2\".hannah.CarStateProto.WindowsEntryR\awindows\x12!\n" +
	"\fowner_roomie\x18\r \x01(\tR\vownerRoomie\x1a8\n" +
	"\n" +
	"DoorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a:\n" +
	"\fWindowsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\".\n" +
	"\vEventFilter\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\xd0\x01\n" +
	"\vHannahEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x124\n" +
	"\tcar_state\x18\n" +
	" \x01(\v2\x15.hannah.CarStateProtoH\x00R\bcarState\x12C\n" +
	"\x0eresident_event\x18\v \x01(\v2\x1a.hannah.ResidentEventProtoH\x00R\rresidentEventB\t\n" +
	"\apayload\"j\n" +
	"\x12ResidentEventProto\x12\x1b\n" +
	"\troomie_id\x18\x01 \x01(\tR\broomieId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\"a\n" +
	"\x0eProxyHeartbeat\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12\x19\n" +
	"\budp_host\x18\x02 \x01(\tR\audpHost\x12\x19\n" +
	"\budp_port\x18\x03 \x01(\x05R\audpPort\"z\n" +
	"\fProxyCommand\x12$\n" +
	"\x03ack\x18\x01 \x01(\v2\x10.hannah.ProxyAckH\x00R\x03ack\x129\n" +
	"\n" +
	"play_audio\x18\x02 \x01(\v2\x18.hannah.PlayAudioCommandH\x00R\tplayAudioB\t\n" +
	"\acommand\"G\n" +
	"\bProxyAck\x12!\n" +
	"\fudp_disabled\x18\x01 \x01(\bR\vudpDisabled\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"m\n" +
	"\x10PlayAudioCommand\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\taudio_pcm\x18\x02 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\"\xb8\x01\n" +
	"\x1bSubmitSatelliteAudioRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x1b\n" +
	"\taudio_pcm\x18\x03 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRate\x12*\n" +
	"\x11speaker_roomie_id\x18\x05 \x01(\tR\x0fspeakerRoomieId\"\xb5\x01\n" +
	"\x1cSubmitSatelliteAudioResponse\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1f\n" +
	"\vintent_name\x18\x03 \x01(\tR\n" +
	"intentName\x12\x1b\n" +
	"\taudio_pcm\x18\x04 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\"\xdb\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06states\x18\x04 \x03(\tR\x06states\x129\n" +
	"\acurrent\x18\x05 \x03(\v2\x1f.hannah.DeviceInfo.CurrentEntryR\acurrent\x1a:\n" +
	"\fCurrentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\bRoomInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\adevices\x18\x03 \x03(\v2\x12.hannah.DeviceInfoR\adevices\"<\n" +
	"\x12GetDevicesResponse\x12&\n" +
	"\x05rooms\x18\x01 \x03(\v2\x10.hannah.RoomInfoR\x05rooms\"_\n" +
	"\x14ControlDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"t\n" +
	"\x17EnrollVoiceprintRequest\x12\x1b\n" +
	"\troomie_id\x18\x01 \x01(\tR\broomieId\x12\x1b\n" +
	"\taudio_pcm\x18\x02 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\"H\n" +
	"\x15SatelliteRegistration\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room2\xed\t\n" +
	"\rHannahService\x12=\n" +
	"\bGetUsers\x12\x17.hannah.GetUsersRequest\x1a\x18.hannah.GetUsersResponse\x127\n" +
	"\aGetUser\x12\x16.hannah.GetUserRequest\x1a\x14.hannah.UserResponse\x12A\n" +
	"\vLinkAccount\x12\x1a.hannah.LinkAccountRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rUnlinkAccount\x12\x1c.hannah.UnlinkAccountRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rSetTrustLevel\x12\x1c.hannah.SetTrustLevelRequest\x1a\x16.hannah.StatusResponse\x127\n" +
	"\n" +
	"GetDevices\x12\r.hannah.Empty\x1a\x1a.hannah.GetDevicesResponse\x12E\n" +
	"\rControlDevice\x12\x1c.hannah.ControlDeviceRequest\x1a\x16.hannah.StatusResponse\x12C\n" +
	"\n" +
	"SubmitText\x12\x19.hannah.SubmitTextRequest\x1a\x1a.hannah.SubmitTextResponse\x12F\n" +
	"\vSubmitVoice\x12\x1a.hannah.SubmitVoiceRequest\x1a\x1b.hannah.SubmitVoiceResponse\x12;\n" +
	"\bAnnounce\x12\x17.hannah.AnnounceRequest\x1a\x16.hannah.StatusResponse\x12=\n" +
	"\rGetSatellites\x12\r.hannah.Empty\x1a\x1d.hannah.GetSatellitesResponse\x126\n" +
	"\vGetCarState\x12\r.hannah.Empty\x1a\x18.hannah.CarStateResponse\x12=\n" +
	"\x0fSubscribeEvents\x12\x13.hannah.EventFilter\x1a\x13.hannah.HannahEvent0\x01\x12A\n" +
	"\rRegisterProxy\x12\x16.hannah.ProxyHeartbeat\x1a\x14.hannah.ProxyCommand(\x010\x01\x12a\n" +
	"\x14SubmitSatelliteAudio\x12#.hannah.SubmitSatelliteAudioRequest\x1a$.hannah.SubmitSatelliteAudioResponse\x12R\n" +
	"\x19NotifySatelliteRegistered\x12\x1d.hannah.SatelliteRegistration\x1a\x16.hannah.StatusResponse\x12L\n" +
	"\x13NotifySatelliteGone\x12\x1d.hannah.SatelliteRegistration\x1a\x16.hannah.StatusResponse\x12K\n" +
	"\x10EnrollVoiceprint\x12\x1f.hannah.EnrollVoiceprintRequest\x1a\x16.hannah.StatusResponseBU\n" +
	"\tio.hannahB\vHannahProtoZ;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_hannah_proto_rawDescOnce sync.Once
	file_hannah_proto_rawDescData []byte
)

func file_hannah_proto_rawDescGZIP() []byte {
	file_hannah_proto_rawDescOnce.Do(func() {
		file_hannah_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hannah_proto_rawDesc), len(file_hannah_proto_rawDesc)))
	})
	return file_hannah_proto_rawDescData
}

var file_hannah_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_hannah_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: hannah.Empty
	(*StatusResponse)(nil),               // 1: hannah.StatusResponse
	(*User)(nil),                         // 2: hannah.User
	(*GetUsersRequest)(nil),              // 3: hannah.GetUsersRequest
	(*GetUsersResponse)(nil),             // 4: hannah.GetUsersResponse
	(*GetUserRequest)(nil),               // 5: hannah.GetUserRequest
	(*LinkedAccountLookup)(nil),          // 6: hannah.LinkedAccountLookup
	(*UserResponse)(nil),                 // 7: hannah.UserResponse
	(*LinkAccountRequest)(nil),           // 8: hannah.LinkAccountRequest
	(*UnlinkAccountRequest)(nil),         // 9: hannah.UnlinkAccountRequest
	(*SetTrustLevelRequest)(nil),         // 10: hannah.SetTrustLevelRequest
	(*SubmitTextRequest)(nil),            // 11: hannah.SubmitTextRequest
	(*SubmitTextResponse)(nil),           // 12: hannah.SubmitTextResponse
	(*SubmitVoiceRequest)(nil),           // 13: hannah.SubmitVoiceRequest
	(*SubmitVoiceResponse)(nil),          // 14: hannah.SubmitVoiceResponse
	(*AnnounceRequest)(nil),              // 15: hannah.AnnounceRequest
	(*Satellite)(nil),                    // 16: hannah.Satellite
	(*GetSatellitesResponse)(nil),        // 17: hannah.GetSatellitesResponse
	(*CarStateResponse)(nil),             // 18: hannah.CarStateResponse
	(*CarStateProto)(nil),                // 19: hannah.CarStateProto
	(*EventFilter)(nil),                  // 20: hannah.EventFilter
	(*HannahEvent)(nil),                  // 21: hannah.HannahEvent
	(*ResidentEventProto)(nil),           // 22: hannah.ResidentEventProto
	(*ProxyHeartbeat)(nil),               // 23: hannah.ProxyHeartbeat
	(*ProxyCommand)(nil),                 // 24: hannah.ProxyCommand
	(*ProxyAck)(nil),                     // 25: hannah.ProxyAck
	(*PlayAudioCommand)(nil),             // 26: hannah.PlayAudioCommand
	(*SubmitSatelliteAudioRequest)(nil),  // 27: hannah.SubmitSatelliteAudioRequest
	(*SubmitSatelliteAudioResponse)(nil), // 28: hannah.SubmitSatelliteAudioResponse
	(*DeviceInfo)(nil),                   // 29: hannah.DeviceInfo
	(*RoomInfo)(nil),                     // 30: hannah.RoomInfo
	(*GetDevicesResponse)(nil),           // 31: hannah.GetDevicesResponse
	(*ControlDeviceRequest)(nil),         // 32: hannah.ControlDeviceRequest
	(*EnrollVoiceprintRequest)(nil),      // 33: hannah.EnrollVoiceprintRequest
	(*SatelliteRegistration)(nil),        // 34: hannah.SatelliteRegistration
	nil,                                  // 35: hannah.User.LinkedAccountsEntry
	nil,                                  // 36: hannah.CarStateProto.DoorsEntry
	nil,                                  // 37: hannah.CarStateProto.WindowsEntry
	nil,                                  // 38: hannah.DeviceInfo.CurrentEntry
}
var file_hannah_proto_depIdxs = []int32{
	35, // 0: hannah.User.linked_accounts:type_name -> hannah.User.LinkedAccountsEntry
	2,  // 1: hannah.GetUsersResponse.users:type_name -> hannah.User
	6,  // 2: hannah.GetUserRequest.linked_account:type_name -> hannah.LinkedAccountLookup
	2,  // 3: hannah.UserResponse.user:type_name -> hannah.User
	16, // 4: hannah.GetSatellitesResponse.satellites:type_name -> hannah.Satellite
	19, // 5: hannah.CarStateResponse.state:type_name -> hannah.CarStateProto
	36, // 6: hannah.CarStateProto.doors:type_name -> hannah.CarStateProto.DoorsEntry
	37, // 7: hannah.CarStateProto.windows:type_name -> hannah.CarStateProto.WindowsEntry
	19, // 8: hannah.HannahEvent.car_state:type_name -> hannah.CarStateProto
	22, // 9: hannah.HannahEvent.resident_event:type_name -> hannah.ResidentEventProto
	25, // 10: hannah.ProxyCommand.ack:type_name -> hannah.ProxyAck
	26, // 11: hannah.ProxyCommand.play_audio:type_name -> hannah.PlayAudioCommand
	38, // 12: hannah.DeviceInfo.current:type_name -> hannah.DeviceInfo.CurrentEntry
	29, // 13: hannah.RoomInfo.devices:type_name -> hannah.DeviceInfo
	30, // 14: hannah.GetDevicesResponse.rooms:type_name -> hannah.RoomInfo
	3,  // 15: hannah.HannahService.GetUsers:input_type -> hannah.GetUsersRequest
	5,  // 16: hannah.HannahService.GetUser:input_type -> hannah.GetUserRequest
	8,  // 17: hannah.HannahService.LinkAccount:input_type -> hannah.LinkAccountRequest
	9,  // 18: hannah.HannahService.UnlinkAccount:input_type -> hannah.UnlinkAccountRequest
	10, // 19: hannah.HannahService.SetTrustLevel:input_type -> hannah.SetTrustLevelRequest
	0,  // 20: hannah.HannahService.GetDevices:input_type -> hannah.Empty
	32, // 21: hannah.HannahService.ControlDevice:input_type -> hannah.ControlDeviceRequest
	11, // 22: hannah.HannahService.SubmitText:input_type -> hannah.SubmitTextRequest
	13, // 23: hannah.HannahService.SubmitVoice:input_type -> hannah.SubmitVoiceRequest
	15, // 24: hannah.HannahService.Announce:input_type -> hannah.AnnounceRequest
	0,  // 25: hannah.HannahService.GetSatellites:input_type -> hannah.Empty
	0,  // 26: hannah.HannahService.GetCarState:input_type -> hannah.Empty
	20, // 27: hannah.HannahService.SubscribeEvents:input_type -> hannah.EventFilter
	23, // 28: hannah.HannahService.RegisterProxy:input_type -> hannah.ProxyHeartbeat
	27, // 29: hannah.HannahService.SubmitSatelliteAudio:input_type -> hannah.SubmitSatelliteAudioRequest
	34, // 30: hannah.HannahService.NotifySatelliteRegistered:input_type -> hannah.SatelliteRegistration
	34, // 31: hannah.HannahService.NotifySatelliteGone:input_type -> hannah.SatelliteRegistration
	33, // 32: hannah.HannahService.EnrollVoiceprint:input_type -> hannah.EnrollVoiceprintRequest
	4,  // 33: hannah.HannahService.GetUsers:output_type -> hannah.GetUsersResponse
	7,  // 34: hannah.HannahService.GetUser:output_type -> hannah.UserResponse
	1,  // 35: hannah.HannahService.LinkAccount:output_type -> hannah.StatusResponse
	1,  // 36: hannah.HannahService.UnlinkAccount:output_type -> hannah.StatusResponse
	1,  // 37: hannah.HannahService.SetTrustLevel:output_type -> hannah.StatusResponse
	31, // 38: hannah.HannahService.GetDevices:output_type -> hannah.GetDevicesResponse
	1,  // 39: hannah.HannahService.ControlDevice:output_type -> hannah.StatusResponse
	12, // 40: hannah.HannahService.SubmitText:output_type -> hannah.SubmitTextResponse
	14, // 41: hannah.HannahService.SubmitVoice:output_type -> hannah.SubmitVoiceResponse
	1,  // 42: hannah.HannahService.Announce:output_type -> hannah.StatusResponse
	17, // 43: hannah.HannahService.GetSatellites:output_type -> hannah.GetSatellitesResponse
	18, // 44: hannah.HannahService.GetCarState:output_type -> hannah.CarStateResponse
	21, // 45: hannah.HannahService.SubscribeEvents:output_type -> hannah.HannahEvent
	24, // 46: hannah.HannahService.RegisterProxy:output_type -> hannah.ProxyCommand
	28, // 47: hannah.HannahService.SubmitSatelliteAudio:output_type -> hannah.SubmitSatelliteAudioResponse
	1,  // 48: hannah.HannahService.NotifySatelliteRegistered:output_type -> hannah.StatusResponse
	1,  // 49: hannah.HannahService.NotifySatelliteGone:output_type -> hannah.StatusResponse
	1,  // 50: hannah.HannahService.EnrollVoiceprint:output_type -> hannah.StatusResponse
	33, // [33:51] is the sub-list for method output_type
	15, // [15:33] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_hannah_proto_init() }
func file_hannah_proto_init() {
	if File_hannah_proto != nil {
		return
	}
	file_hannah_proto_msgTypes[5].OneofWrappers = []any{
		(*GetUserRequest_RoomieId)(nil),
		(*GetUserRequest_Uuid)(nil),
		(*GetUserRequest_LinkedAccount)(nil),
	}
	file_hannah_proto_msgTypes[21].OneofWrappers = []any{
		(*HannahEvent_CarState)(nil),
		(*HannahEvent_ResidentEvent)(nil),
	}
	file_hannah_proto_msgTypes[24].OneofWrappers = []any{
		(*ProxyCommand_Ack)(nil),
		(*ProxyCommand_PlayAudio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hannah_proto_rawDesc), len(file_hannah_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hannah_proto_goTypes,
		DependencyIndexes: file_hannah_proto_depIdxs,
		MessageInfos:      file_hannah_proto_msgTypes,
	}.Build()
	File_hannah_proto = out.File
	file_hannah_proto_goTypes = nil
	file_hannah_proto_depIdxs = nil
}
