// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: hannah.proto

package hannah

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HannahService_GetUsers_FullMethodName                  = "/hannah.HannahService/GetUsers"
	HannahService_GetUser_FullMethodName                   = "/hannah.HannahService/GetUser"
	HannahService_LinkAccount_FullMethodName               = "/hannah.HannahService/LinkAccount"
	HannahService_UnlinkAccount_FullMethodName             = "/hannah.HannahService/UnlinkAccount"
	HannahService_SetTrustLevel_FullMethodName             = "/hannah.HannahService/SetTrustLevel"
	HannahService_GetDevices_FullMethodName                = "/hannah.HannahService/GetDevices"
	HannahService_ControlDevice_FullMethodName             = "/hannah.HannahService/ControlDevice"
	HannahService_SubmitText_FullMethodName                = "/hannah.HannahService/SubmitText"
	HannahService_SubmitVoice_FullMethodName               = "/hannah.HannahService/SubmitVoice"
	HannahService_Announce_FullMethodName                  = "/hannah.HannahService/Announce"
	HannahService_GetSatellites_FullMethodName             = "/hannah.HannahService/GetSatellites"
	HannahService_GetCarState_FullMethodName               = "/hannah.HannahService/GetCarState"
	HannahService_SubscribeEvents_FullMethodName           = "/hannah.HannahService/SubscribeEvents"
	HannahService_RegisterProxy_FullMethodName             = "/hannah.HannahService/RegisterProxy"
	HannahService_SubmitSatelliteAudio_FullMethodName      = "/hannah.HannahService/SubmitSatelliteAudio"
	HannahService_NotifySatelliteRegistered_FullMethodName = "/hannah.HannahService/NotifySatelliteRegistered"
	HannahService_NotifySatelliteGone_FullMethodName       = "/hannah.HannahService/NotifySatelliteGone"
	HannahService_EnrollVoiceprint_FullMethodName          = "/hannah.HannahService/EnrollVoiceprint"
)

// HannahServiceClient is the client API for HannahService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HannahServiceClient interface {
	// --- User Registry ---
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	LinkAccount(ctx context.Context, in *LinkAccountRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UnlinkAccount(ctx context.Context, in *UnlinkAccountRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	SetTrustLevel(ctx context.Context, in *SetTrustLevelRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// --- Device Control Menu ---
	// Returns all rooms and devices with current state — for building control menus.
	GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDevicesResponse, error)
	// Directly set a device state (bypasses NLU). Trust level check is done by the caller.
	ControlDevice(ctx context.Context, in *ControlDeviceRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// --- Control ---
	// Submit a plain-text command; Hannah processes it through NLU and returns the answer.
	SubmitText(ctx context.Context, in *SubmitTextRequest, opts ...grpc.CallOption) (*SubmitTextResponse, error)
	// Submit a voice message (OGG/Opus bytes); Hannah does STT → NLU → TTS and returns the result.
	SubmitVoice(ctx context.Context, in *SubmitVoiceRequest, opts ...grpc.CallOption) (*SubmitVoiceResponse, error)
	// Send a TTS announcement to one satellite or all ("all").
	Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// List all currently registered UDP satellites.
	GetSatellites(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSatellitesResponse, error)
	// --- Car ---
	// Returns the current cached car state (available=false if no data received yet).
	GetCarState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CarStateResponse, error)
	// --- Event stream ---
	// Opens a server-side stream; Hannah pushes events as they occur.
	// Pass event_types to filter (empty = all events).
	// Known event types: "car.parked", "resident.arrived", "resident.departed"
	SubscribeEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HannahEvent], error)
	// --- Satellite Proxy (Go gRPC proxy) ---
	// Bidirectional keepalive stream. Proxy sends heartbeats; Hannah sends TTS
	// audio commands back (for announcements). While this stream is open, Hannah
	// disables its own UDP server. If the stream drops, Hannah re-enables UDP.
	RegisterProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyHeartbeat, ProxyCommand], error)
	// Submit a complete satellite audio session for processing.
	// Hannah runs the full pipeline (STT → NLU → TTS → MQTT status) and returns
	// the result so the proxy can play TTS audio back to the satellite.
	SubmitSatelliteAudio(ctx context.Context, in *SubmitSatelliteAudioRequest, opts ...grpc.CallOption) (*SubmitSatelliteAudioResponse, error)
	// Notify Hannah that a satellite registered or disconnected via the proxy.
	// Hannah updates its room registry (hannah/rooms MQTT) immediately.
	NotifySatelliteRegistered(ctx context.Context, in *SatelliteRegistration, opts ...grpc.CallOption) (*StatusResponse, error)
	NotifySatelliteGone(ctx context.Context, in *SatelliteRegistration, opts ...grpc.CallOption) (*StatusResponse, error)
	// --- Speaker Enrollment ---
	EnrollVoiceprint(ctx context.Context, in *EnrollVoiceprintRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type hannahServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHannahServiceClient(cc grpc.ClientConnInterface) HannahServiceClient {
	return &hannahServiceClient{cc}
}

func (c *hannahServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, HannahService_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, HannahService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) LinkAccount(ctx context.Context, in *LinkAccountRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_LinkAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) UnlinkAccount(ctx context.Context, in *UnlinkAccountRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_UnlinkAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) SetTrustLevel(ctx context.Context, in *SetTrustLevelRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_SetTrustLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevicesResponse)
	err := c.cc.Invoke(ctx, HannahService_GetDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) ControlDevice(ctx context.Context, in *ControlDeviceRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_ControlDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) SubmitText(ctx context.Context, in *SubmitTextRequest, opts ...grpc.CallOption) (*SubmitTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTextResponse)
	err := c.cc.Invoke(ctx, HannahService_SubmitText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) SubmitVoice(ctx context.Context, in *SubmitVoiceRequest, opts ...grpc.CallOption) (*SubmitVoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitVoiceResponse)
	err := c.cc.Invoke(ctx, HannahService_SubmitVoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_Announce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) GetSatellites(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSatellitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSatellitesResponse)
	err := c.cc.Invoke(ctx, HannahService_GetSatellites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) GetCarState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CarStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CarStateResponse)
	err := c.cc.Invoke(ctx, HannahService_GetCarState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) SubscribeEvents(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HannahEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HannahService_ServiceDesc.Streams[0], HannahService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventFilter, HannahEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HannahService_SubscribeEventsClient = grpc.ServerStreamingClient[HannahEvent]

func (c *hannahServiceClient) RegisterProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyHeartbeat, ProxyCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HannahService_ServiceDesc.Streams[1], HannahService_RegisterProxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyHeartbeat, ProxyCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HannahService_RegisterProxyClient = grpc.BidiStreamingClient[ProxyHeartbeat, ProxyCommand]

func (c *hannahServiceClient) SubmitSatelliteAudio(ctx context.Context, in *SubmitSatelliteAudioRequest, opts ...grpc.CallOption) (*SubmitSatelliteAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSatelliteAudioResponse)
	err := c.cc.Invoke(ctx, HannahService_SubmitSatelliteAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) NotifySatelliteRegistered(ctx context.Context, in *SatelliteRegistration, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_NotifySatelliteRegistered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) NotifySatelliteGone(ctx context.Context, in *SatelliteRegistration, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_NotifySatelliteGone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hannahServiceClient) EnrollVoiceprint(ctx context.Context, in *EnrollVoiceprintRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HannahService_EnrollVoiceprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HannahServiceServer is the server API for HannahService service.
// All implementations must embed UnimplementedHannahServiceServer
// for forward compatibility.
type HannahServiceServer interface {
	// --- User Registry ---
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	LinkAccount(context.Context, *LinkAccountRequest) (*StatusResponse, error)
	UnlinkAccount(context.Context, *UnlinkAccountRequest) (*StatusResponse, error)
	SetTrustLevel(context.Context, *SetTrustLevelRequest) (*StatusResponse, error)
	// --- Device Control Menu ---
	// Returns all rooms and devices with current state — for building control menus.
	GetDevices(context.Context, *Empty) (*GetDevicesResponse, error)
	// Directly set a device state (bypasses NLU). Trust level check is done by the caller.
	ControlDevice(context.Context, *ControlDeviceRequest) (*StatusResponse, error)
	// --- Control ---
	// Submit a plain-text command; Hannah processes it through NLU and returns the answer.
	SubmitText(context.Context, *SubmitTextRequest) (*SubmitTextResponse, error)
	// Submit a voice message (OGG/Opus bytes); Hannah does STT → NLU → TTS and returns the result.
	SubmitVoice(context.Context, *SubmitVoiceRequest) (*SubmitVoiceResponse, error)
	// Send a TTS announcement to one satellite or all ("all").
	Announce(context.Context, *AnnounceRequest) (*StatusResponse, error)
	// List all currently registered UDP satellites.
	GetSatellites(context.Context, *Empty) (*GetSatellitesResponse, error)
	// --- Car ---
	// Returns the current cached car state (available=false if no data received yet).
	GetCarState(context.Context, *Empty) (*CarStateResponse, error)
	// --- Event stream ---
	// Opens a server-side stream; Hannah pushes events as they occur.
	// Pass event_types to filter (empty = all events).
	// Known event types: "car.parked", "resident.arrived", "resident.departed"
	SubscribeEvents(*EventFilter, grpc.ServerStreamingServer[HannahEvent]) error
	// --- Satellite Proxy (Go gRPC proxy) ---
	// Bidirectional keepalive stream. Proxy sends heartbeats; Hannah sends TTS
	// audio commands back (for announcements). While this stream is open, Hannah
	// disables its own UDP server. If the stream drops, Hannah re-enables UDP.
	RegisterProxy(grpc.BidiStreamingServer[ProxyHeartbeat, ProxyCommand]) error
	// Submit a complete satellite audio session for processing.
	// Hannah runs the full pipeline (STT → NLU → TTS → MQTT status) and returns
	// the result so the proxy can play TTS audio back to the satellite.
	SubmitSatelliteAudio(context.Context, *SubmitSatelliteAudioRequest) (*SubmitSatelliteAudioResponse, error)
	// Notify Hannah that a satellite registered or disconnected via the proxy.
	// Hannah updates its room registry (hannah/rooms MQTT) immediately.
	NotifySatelliteRegistered(context.Context, *SatelliteRegistration) (*StatusResponse, error)
	NotifySatelliteGone(context.Context, *SatelliteRegistration) (*StatusResponse, error)
	// --- Speaker Enrollment ---
	EnrollVoiceprint(context.Context, *EnrollVoiceprintRequest) (*StatusResponse, error)
	mustEmbedUnimplementedHannahServiceServer()
}

// UnimplementedHannahServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHannahServiceServer struct{}

func (UnimplementedHannahServiceServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedHannahServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedHannahServiceServer) LinkAccount(context.Context, *LinkAccountRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkAccount not implemented")
}
func (UnimplementedHannahServiceServer) UnlinkAccount(context.Context, *UnlinkAccountRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkAccount not implemented")
}
func (UnimplementedHannahServiceServer) SetTrustLevel(context.Context, *SetTrustLevelRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTrustLevel not implemented")
}
func (UnimplementedHannahServiceServer) GetDevices(context.Context, *Empty) (*GetDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedHannahServiceServer) ControlDevice(context.Context, *ControlDeviceRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ControlDevice not implemented")
}
func (UnimplementedHannahServiceServer) SubmitText(context.Context, *SubmitTextRequest) (*SubmitTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitText not implemented")
}
func (UnimplementedHannahServiceServer) SubmitVoice(context.Context, *SubmitVoiceRequest) (*SubmitVoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitVoice not implemented")
}
func (UnimplementedHannahServiceServer) Announce(context.Context, *AnnounceRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Announce not implemented")
}
func (UnimplementedHannahServiceServer) GetSatellites(context.Context, *Empty) (*GetSatellitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSatellites not implemented")
}
func (UnimplementedHannahServiceServer) GetCarState(context.Context, *Empty) (*CarStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCarState not implemented")
}
func (UnimplementedHannahServiceServer) SubscribeEvents(*EventFilter, grpc.ServerStreamingServer[HannahEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedHannahServiceServer) RegisterProxy(grpc.BidiStreamingServer[ProxyHeartbeat, ProxyCommand]) error {
	return status.Error(codes.Unimplemented, "method RegisterProxy not implemented")
}
func (UnimplementedHannahServiceServer) SubmitSatelliteAudio(context.Context, *SubmitSatelliteAudioRequest) (*SubmitSatelliteAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSatelliteAudio not implemented")
}
func (UnimplementedHannahServiceServer) NotifySatelliteRegistered(context.Context, *SatelliteRegistration) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifySatelliteRegistered not implemented")
}
func (UnimplementedHannahServiceServer) NotifySatelliteGone(context.Context, *SatelliteRegistration) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifySatelliteGone not implemented")
}
func (UnimplementedHannahServiceServer) EnrollVoiceprint(context.Context, *EnrollVoiceprintRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollVoiceprint not implemented")
}
func (UnimplementedHannahServiceServer) mustEmbedUnimplementedHannahServiceServer() {}
func (UnimplementedHannahServiceServer) testEmbeddedByValue()                       {}

// UnsafeHannahServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HannahServiceServer will
// result in compilation errors.
type UnsafeHannahServiceServer interface {
	mustEmbedUnimplementedHannahServiceServer()
}

func RegisterHannahServiceServer(s grpc.ServiceRegistrar, srv HannahServiceServer) {
	// If the following call panics, it indicates UnimplementedHannahServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HannahService_ServiceDesc, srv)
}

func _HannahService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_LinkAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).LinkAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_LinkAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).LinkAccount(ctx, req.(*LinkAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_UnlinkAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).UnlinkAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_UnlinkAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).UnlinkAccount(ctx, req.(*UnlinkAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_SetTrustLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTrustLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).SetTrustLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_SetTrustLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).SetTrustLevel(ctx, req.(*SetTrustLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_GetDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).GetDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_ControlDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).ControlDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_ControlDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).ControlDevice(ctx, req.(*ControlDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_SubmitText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).SubmitText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_SubmitText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).SubmitText(ctx, req.(*SubmitTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_SubmitVoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitVoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).SubmitVoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_SubmitVoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).SubmitVoice(ctx, req.(*SubmitVoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_Announce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).Announce(ctx, req.(*AnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_GetSatellites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).GetSatellites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_GetSatellites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).GetSatellites(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_GetCarState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).GetCarState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_GetCarState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).GetCarState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HannahServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[EventFilter, HannahEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HannahService_SubscribeEventsServer = grpc.ServerStreamingServer[HannahEvent]

func _HannahService_RegisterProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HannahServiceServer).RegisterProxy(&grpc.GenericServerStream[ProxyHeartbeat, ProxyCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HannahService_RegisterProxyServer = grpc.BidiStreamingServer[ProxyHeartbeat, ProxyCommand]

func _HannahService_SubmitSatelliteAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSatelliteAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).SubmitSatelliteAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_SubmitSatelliteAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).SubmitSatelliteAudio(ctx, req.(*SubmitSatelliteAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_NotifySatelliteRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatelliteRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).NotifySatelliteRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_NotifySatelliteRegistered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).NotifySatelliteRegistered(ctx, req.(*SatelliteRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_NotifySatelliteGone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SatelliteRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).NotifySatelliteGone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_NotifySatelliteGone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).NotifySatelliteGone(ctx, req.(*SatelliteRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _HannahService_EnrollVoiceprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollVoiceprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HannahServiceServer).EnrollVoiceprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HannahService_EnrollVoiceprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HannahServiceServer).EnrollVoiceprint(ctx, req.(*EnrollVoiceprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HannahService_ServiceDesc is the grpc.ServiceDesc for HannahService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HannahService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hannah.HannahService",
	HandlerType: (*HannahServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _HannahService_GetUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _HannahService_GetUser_Handler,
		},
		{
			MethodName: "LinkAccount",
			Handler:    _HannahService_LinkAccount_Handler,
		},
		{
			MethodName: "UnlinkAccount",
			Handler:    _HannahService_UnlinkAccount_Handler,
		},
		{
			MethodName: "SetTrustLevel",
			Handler:    _HannahService_SetTrustLevel_Handler,
		},
		{
			MethodName: "GetDevices",
			Handler:    _HannahService_GetDevices_Handler,
		},
		{
			MethodName: "ControlDevice",
			Handler:    _HannahService_ControlDevice_Handler,
		},
		{
			MethodName: "SubmitText",
			Handler:    _HannahService_SubmitText_Handler,
		},
		{
			MethodName: "SubmitVoice",
			Handler:    _HannahService_SubmitVoice_Handler,
		},
		{
			MethodName: "Announce",
			Handler:    _HannahService_Announce_Handler,
		},
		{
			MethodName: "GetSatellites",
			Handler:    _HannahService_GetSatellites_Handler,
		},
		{
			MethodName: "GetCarState",
			Handler:    _HannahService_GetCarState_Handler,
		},
		{
			MethodName: "SubmitSatelliteAudio",
			Handler:    _HannahService_SubmitSatelliteAudio_Handler,
		},
		{
			MethodName: "NotifySatelliteRegistered",
			Handler:    _HannahService_NotifySatelliteRegistered_Handler,
		},
		{
			MethodName: "NotifySatelliteGone",
			Handler:    _HannahService_NotifySatelliteGone_Handler,
		},
		{
			MethodName: "EnrollVoiceprint",
			Handler:    _HannahService_EnrollVoiceprint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _HannahService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RegisterProxy",
			Handler:       _HannahService_RegisterProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hannah.proto",
}
